baseURL = 'https://mysheepy.github.io/'
languageCode = 'zh-cn'
title = '緜阳绵羊'
theme = "hugo-coder"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "mysheepy-github-io"

[markup.highlight]
style = "github-dark"

[params]
  author = "緜阳绵羊"
  info = "睡前必须玩一把游戏，不同意的请举手。没有……没有……没有……通过！"
  description = "肥宅真的肥"
  keywords = "blog,personal"
  #avatarurl = "images/avatar.jpg"
  gravatar = "mysheepy@outlook.jp"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/mysheepy/"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/mysheepy/"

# Menu links
[[menu.main]]
  name = "博客"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "关於"
  weight = 2
  url = "about/"
